version: '3'

x-common:
  &default-common
  build:
    context: .
  restart: always
  volumes:
    - ./data:/data
  env_file:
    - .env
  logging:
    options:
      max-size: "100m"
      max-file: "5"

services:
  fetcher:
    <<: *default-common
    working_dir: /fetcher
    command: python3 -u ./fetcher.py
